# Generated by Django 4.2.1 on 2023-05-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='useroffer',
            old_name='user',
            new_name='person',
        ),
    ]
