# Generated by Django 4.2.1 on 2023-05-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_rename_user_person_rename_user_useroffer_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
