# Generated by Django 4.2.1 on 2023-06-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_offer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
    ]
